ExternalStorageProvider: fix unmount storage failed from DocumentUI
The Same Problem in SDK12.
commit 180f1eaa3cad595d85fa66d6b5b6453bbc65ed9c

You either need MANAGE_USERS, CREATE_USERS, or QUERY_USERS permission to: query user
java.lang.SecurityException: You either need MANAGE_USERS, CREATE_USERS, or QUERY_USERS permission to: query user
        at com.android.server.pm.UserManagerService.checkQueryOrCreateUsersPermission(UserManagerService.java:2796)
        at com.android.server.pm.UserManagerService.getUserInfo(UserManagerService.java:1427)
        at android.os.UserManager.getUserInfo(UserManager.java:2992)
        at com.android.server.storage.StorageSessionController.getConnectionUserIdForVolume(StorageSessionController.java:86)
        at com.android.server.storage.StorageSessionController.onVolumeRemove(StorageSessionController.java:222)
        at com.android.server.storage.StorageSessionController.onVolumeUnmount(StorageSessionController.java:248)
        at com.android.server.StorageManagerService.unmount(StorageManagerService.java:2404)
        at com.android.server.StorageManagerService.unmount(StorageManagerService.java:2391)
        at android.os.storage.IStorageManager$Stub.onTransact(IStorageManager.java:728)
        at android.os.Binder.execTransactInternal(Binder.java:1280)
        at android.os.Binder.execTransact(Binder.java:1244)

Change-Id: I4331674bcb7b183e8ce426f607cfd10cb3823d7f
Signed-off-by: Jake Wu <jake.wu@rock-chips.com>